Repository lsc-project/lsc, pull requests merged in 2020-02, with the labels that each got.

#112 Force HSQLDB to listen on localhost
  bin/hsqldb
Labels: enhancement

#114 Create LSC group and user as system
  src/install/lsc-core.spec
Labels: packaging

#113 Create LSC group and user as system
  src/install/debian/lsc.postinst
Labels: packaging

#115 Enhancement for #69 Fix Null pointer thrown in job containing multiple tasks with database destinations and sync options.
  src/main/java/org/lsc/service/AbstractJdbcDstService.java
Labels: bug
