Repository lsc-project/lsc, pull requests merged in 2024-05, with the labels that each got.

#276 remove explicit `js:` engine in tests (#275)
  src/test/resources/etc/lsc.xml
Labels: bug, Java compatibilty

#274 Don't modify the files in postinst but rather at the build step in deb package (#273)
  src/install/debian/lsc.postinst
  src/install/debian/rules
Labels: enhancement, packaging

#269 fix: sample code doesn't run from Debian package
  sample/hsqldb/bin/lsc-sample
  sample/ldap2hsqldb/bin/lsc-sample
Labels: bug

#290 Update windows scripts
  bin/lsc-agent.bat
  bin/lsc-agent.cmd
  bin/lsc.bat
  bin/lsc.cmd
  doc/man/html/lsc-agent.1.html
  doc/man/html/lsc.1.html
  doc/man/man1/lsc-agent.1
  doc/man/man1/lsc.1
  doc/man/src/lsc-agent.1.xml
  doc/man/src/lsc.1.xml
  sample/ad/README.txt
  sample/asyncldap/README.txt
  sample/hsqldb/bin/lsc-sample.bat
Labels: enhancement
