Repository lsc-project/lsc, pull requests merged in 2025-04, with the labels that each got.

#391 Fix the controls addition (#375)
  src/main/java/org/lsc/jndi/JndiServices.java
Labels: bug

#387 remove izpack (#386)
  pom.xml
  src/install/install.xml
Labels: packaging

#392 Use better sample data
  sample/hsqldb/sample.csv
  sample/ldap2hsqldb/etc/test.ldif
  src/test/java/org/lsc/db2ldap/Jdbc2LdapSyncTest.java
Labels: documentation

#395 do not copy systemd files into /usr/lib/lsc (#393)
  src/install/debian/lsc.install
  src/install/lsc.spec
Labels: packaging

#397 Force compression alg for Debian package
  src/install/debian/rules
Labels: packaging
