Repository lsc-project/lsc, pull requests merged in 2025-02, with the labels that each got.

#324 fix slow performance on graalvm with jdk11 (#322)
  pom.xml
Labels: bug

#299 Fixed bug override globally configured pageSize variable in the middle of the code
  src/main/java/org/lsc/jndi/JndiServices.java
Labels: bug

#347 make github unit tests run in parallel + fix build for jdk 21 (#346)
  .github/workflows/maven.yml
  pom.xml
Labels: packaging

#352 package graalvm dependencies (#287)
  bin/lsc
  pom.xml
  src/install/debian/lsc.install
  src/install/debian/rules
  src/install/lsc.spec
  src/main/assembly/dist.xml
Labels: enhancement, NGI

#334 SAMPLE_HOME can contain spaces
  sample/hsqldb/bin/lsc-sample
Labels: bug

#301 Provide a cleaner lsc.xml sample file
  etc/lsc.xml-sample
Labels: enhancement

#361 improve jscript prefix identifier and test the graalvm loading (#360)
  src/main/java/org/lsc/utils/ScriptingEvaluator.java
  src/test/java/org/lsc/utils/ScriptingEvaluatorTest.java
Labels: enhancement

#362 Updated the LICENSE file, added the NOTICE file (#328)
  LICENSE.txt
  NOTICE.txt
Labels: dependencies, NGI

#366 Fix SimpleSynchronize init() method can be quite slow (#332)
  src/main/java/org/lsc/SimpleSynchronize.java
  src/test/java/org/lsc/jmx/LscJmxTest.java
Labels: enhancement
